name: "Dev: Build Qubership Envgene Base Modules dockerimage"

run-name: Build Qubership Envgene Base Modules dockerimage on commit ${{ github.sha }}

on:
  workflow_dispatch:
    inputs:
      build-base-modules:
        description: 'Build Qubership Envgene Base Modules dockerimage'
        required: false
        default: true
        type: boolean
  push: null

env:
  REGISTRY: ghcr.io
  CI_PROJECT_DIR: ${{ github.workspace }}

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  conventional-commits:
    permissions:
      contents: read
      packages: write
      statuses: write
      pull-requests: read
    uses: ./.github/workflows/pr-conventional-commits.yaml

  link-check:
    needs: [conventional-commits]
    permissions:
      contents: read
      packages: write
      statuses: write
    uses: ./.github/workflows/link-checker.yaml

  linters:
    needs: [conventional-commits]
    permissions:
      contents: read
      packages: write
      statuses: write
    uses: ./.github/workflows/super-linter.yaml
    with:
      full_scan: false

  build-base-modules:
    needs: [linters, link-check]
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.build-base-modules == 'true') || (github.event_name == 'push' && (contains(github.event.head_commit.message, 'feat:') || contains(github.event.head_commit.message, 'fix:') || contains(github.event.head_commit.message, 'BREAKING CHANGE')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    outputs:
      custom_tag: ${{ steps.build-base-modules.outputs.custom_tag }}
      branch_tag: ${{ steps.build-base-modules.outputs.branch_tag }}
      timestamp: ${{ steps.build-base-modules.outputs.timestamp }}
      branch_latest_tag: ${{ steps.build-base-modules.outputs.branch_latest_tag }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Qubership Envgene Base Modules Docker Image
      uses: ./.github/actions/build-base-modules
      id: build-base-modules
      with:
        registry: ${{ env.REGISTRY }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
